export const dom = {
    radio_numbers: document.querySelectorAll('input[name="num_students"]'),
    input_striker_table: document.querySelector("#input_striker_table"),
    input_special_table: document.querySelector("#input_special_table"),
    striker_graph: document.querySelector("#striker_graph"),
    special_graph: document.querySelector("#special_graph"),
    striker_info: document.querySelector("#striker_info"),
    special_info: document.querySelector("#special_info"),
    class_box: document.querySelector("#class-box"),
    info: document.querySelector("#info"),
    main: document.querySelector("#main"),
    mainbox: document.querySelector("#mainbox"),
    base: document.querySelector("#base"),
    extra: document.querySelectorAll(".extra"),
    get_title: document.querySelector("#get_title"),
    btn_title: document.querySelector("#btn_title"),
    set_title: document.querySelector("#set_title"),
    download: document.querySelector("#download"),
};